#!/bin/bash
# Performs some post-build steps.
# $1 is expected to be set to the build output folder.

deploymentDir="$(dirname "$0")/Deployment"

. "$(dirname "$0")/../Common/do-deploy"

chmod u+x $deploymentDir/ctlab
