#!/bin/bash
# Performs some post-build steps.
# Intended to be source-invoked by that component's deploy script.
# $1 is expected to be set to the build output folder.

set -e
trap "exit" INT TERM EXIT

if [ $# -ne 1 ]; then
    echo "Usage: $0 <buildFolder>"
    exit
fi

projectDir=$(dirname "$0")
sourceDir="$1"
deploymentDir="$projectDir/Deployment"
artifactsDir="$projectDir/Artifacts"

[ ! -d $deploymentDir ] && mkdir $deploymentDir
cp --preserve=timestamps $sourceDir/* $deploymentDir
cp --preserve=timestamps $artifactsDir/* $deploymentDir
